### ISSUE TITLE
XML batch import failure

### ISSUE THREAD

**Issue by thiviyanT** [samuell/rdf2smw#11]
I would like to import a list of RDF's into my Semantic MediaWiki. As instructed in the [guide](https://github.com/rdfio/rdf2smw), I have converted my triples into XML files. Once I attempt to import the first XML file (templates) using the command ` php wiki/htdocs/maintenance/importDump.php semantic_mediawiki_pages_templates.xml` I am getting the following error message:

```
[e52017568cfd4bfeb7a15a95] [no req]   Wikimedia\Rdbms\DBConnectionError from line 769 of /wiki/htdocs/includes/libs/rdbms/database/Database.php: Cannot access the database: No such file or directory (localhost:3306)
Backtrace:
#0 /wiki/htdocs/includes/libs/rdbms/loadbalancer/LoadBalancer.php(995): Wikimedia\Rdbms\Database->reportConnectionError(string)
#1 /wiki/htdocs/includes/libs/rdbms/loadbalancer/LoadBalancer.php(666): Wikimedia\Rdbms\LoadBalancer->reportConnectionError()
#2 /wiki/htdocs/includes/GlobalFunctions.php(3062): Wikimedia\Rdbms\LoadBalancer->getConnection(integer, array, boolean)
#3 /wiki/htdocs/includes/cache/localisation/LCStoreDB.php(45): wfGetDB(integer)
#4 /wiki/htdocs/includes/cache/localisation/LocalisationCache.php(414): LCStoreDB->get(string, string)
#5 /wiki/htdocs/includes/cache/localisation/LocalisationCache.php(460): LocalisationCache->isExpired(string)
#6 /wiki/htdocs/includes/cache/localisation/LocalisationCache.php(336): LocalisationCache->initLanguage(string)
#7 /wiki/htdocs/includes/cache/localisation/LocalisationCache.php(273): LocalisationCache->loadItem(string, string)
#8 /wiki/htdocs/languages/Language.php(600): LocalisationCache->getItem(string, string)
#9 /wiki/htdocs/includes/title/MediaWikiTitleCodec.php(86): Language->needsGenderDistinction()
#10 /wiki/htdocs/includes/title/MediaWikiTitleCodec.php(217): MediaWikiTitleCodec->getNamespaceName(integer, string)
#11 /wiki/htdocs/includes/cache/LinkCache.php(234): MediaWikiTitleCodec->getPrefixedDBkey(Title)
#12 /wiki/htdocs/includes/Title.php(3233): LinkCache->addLinkObj(Title)
#13 /wiki/htdocs/includes/Title.php(4320): Title->getArticleID(integer)
#14 /wiki/htdocs/extensions/SemanticMediaWiki/src/PermissionPthValidator.php(80): Title->exists()
#15 /wiki/htdocs/extensions/SemanticMediaWiki/src/PermissionPthValidator.php(57): SMW\PermissionPthValidator->checkUserPermissionOn(Title, User, string, array)
#16 /wiki/htdocs/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(544): SMW\PermissionPthValidator->checkQuickPermissionOn(Title, User, string, array)
#17 [internal function]: SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(Title, User, string, array, boolean, boolean)
#18 /wiki/htdocs/includes/Hooks.php(186): call_user_func_array(Closure, array)
#19 /wiki/htdocs/includes/Title.php(1987): Hooks::run(string, array)
#20 /wiki/htdocs/includes/Title.php(2533): Title->checkQuickPermissions(string, User, array, string, boolean)
#21 /wiki/htdocs/includes/Title.php(1936): Title->getUserPermissionsErrorsInternal(string, User, string, boolean)
#22 /wiki/htdocs/includes/import/WikiImporter.php(1068): Title->userCan(string)
#23 /wiki/htdocs/includes/import/WikiImporter.php(755): WikiImporter->processTitle(string, string)
#24 /wiki/htdocs/includes/import/WikiImporter.php(577): WikiImporter->handlePage()
#25 /wiki/htdocs/maintenance/importDump.php(322): WikiImporter->doImport()
#26 /wiki/htdocs/maintenance/importDump.php(269): BackupReader->importFromHandle(resource)
#27 /wiki/htdocs/maintenance/importDump.php(106): BackupReader->importFromFile(string)
#28 /wiki/htdocs/maintenance/doMaintenance.php(111): BackupReader->execute()
#29 /wiki/htdocs/maintenance/importDump.php(327): require_once(string)
#30 {main}
```

Can someone please help me understand this error message?

Thanks,
TT

--------------------------------------

List of tools that I am using:
- Apache Web Server - Port 8080
- MediaWiki 1.29.1
- Semantic MediaWiki 2.5.4
- PHP 7.0.22
- MySQL 5.6.37 - Port 3306
- RDFIO 3.0.2
- rdf2smw v0.6

**Comment by thiviyanT** [comment]
I found out what the meaning of the error log thanks to [Ciencia Al Poder](https://www.mediawiki.org/wiki/Topic:R39ey1ut17circ5x) and I have dealt with it.

This is not an issue caused by the rdf2sem!
